import * as React from "react";
import clsx from "clsx";
import type { NextPage } from "next";
import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";
import * as API from "Services/api";

const Home: NextPage = () => {
  const [ballots, setBallots] = React.useState<any[]>([]);
  const [selectedNominees, setSelectedNominees] = React.useState<any>({});

  const selectNominee = (categoryId: string, nomineeId: string) => () => {
    const copySelectedNominees: any = { ...selectedNominees };
    copySelectedNominees[categoryId] = nomineeId;
    setSelectedNominees(copySelectedNominees);
  };

  React.useEffect(() => {
    (async () => {
      const response = await API.getBallots();
      if (response.ok) {
        setBallots(response.items);
      }
    })();
  }, []);

  const isSelectedNominee = (categoryId: string, nomineeId: string) =>
    selectedNominees[categoryId] === nomineeId;

  return (
    <div className={styles.container}>
      <Head>
        <title>Take Home Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {ballots.map((ballot) => (
          <div key={ballot.id}>
            <h1>{ballot.title}</h1>
            {ballot.items.map((item: any) => (
              <div
                key={item.id}
                className={clsx(
                  isSelectedNominee(ballot.id, item.id) &&
                    "border-2 border-red-500"
                )}
              >
                <h3
                  className="ml-4"
                  onClick={selectNominee(ballot.id, item.id)}
                >
                  {item.title}
                </h3>
              </div>
            ))}
          </div>
        ))}
      </main>
    </div>
  );
};

export default Home;
